# Generated by Django 5.0.1 on 2024-01-25 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquetes", "0002_alter_perguntaemuso_eleicao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcoes",
            name="pergunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opcoes",
                to="enquetes.pergunta",
            ),
        ),
    ]
