# Generated by Django 5.0.1 on 2024-01-25 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enquetes", "0004_enquete_usuarios_alter_perguntaemuso_eleicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perguntaemuso",
            name="enqute_em_uso",
        ),
    ]
