# Generated by Django 5.0.1 on 2024-01-26 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquetes", "0005_remove_perguntaemuso_enqute_em_uso"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquete",
            name="aberto",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="perguntaemuso",
            name="eleicao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escolhda_em_pergunta",
                to="enquetes.opcoes",
            ),
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="votos",
                        to="enquetes.enquete",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="votos",
                        to="enquetes.pergunta",
                    ),
                ),
                (
                    "resposta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votos",
                        to="enquetes.opcoes",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
