# Generated by Django 5.0.1 on 2024-01-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquetes", "0006_enquete_aberto_alter_perguntaemuso_eleicao_voto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voto",
            name="resposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="votos",
                to="enquetes.opcoes",
            ),
        ),
        migrations.DeleteModel(
            name="PerguntaEmUso",
        ),
    ]
