# Generated by Django 5.0.1 on 2024-01-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquetes", "0007_alter_voto_resposta_delete_perguntaemuso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name="enquete",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquetes",
                to="enquetes.categoria",
            ),
        ),
    ]
